### ISSUE TITLE
Human experiments documentation

### ISSUE THREAD

**Issue by eliaszwang** [cogtoolslab/physics-benchmarking-neurips2021#43]
- [x]  write markdown with steps
- [x]  Link osf
~~add documentation for server-side code~~
~~add documentation for metadata generation notebooks & S3 upload~~
- [x] update readme on main page, point to more detailed readme inside `./experiments`

### Check
- [x]  Can we follow these instructions to replicate our human experimental setup using exactly the same infrastructure **[@sradwan15](https://github.com/sradwan15)**
~~Can we generate the input files needed for analysis, given experimental data inside a mongoDB?~~
- [x]  Can we use this codebase to extend to variants of our human experiments? **

**Comment by felixbinder** [comment]
https://github.com/cogtoolslab/physics-benchmarking-neurips2021/blob/master/experiments/README.md
