### ISSUE TITLE
Instructions for Creating / Connecting to MongoDB

### ISSUE THREAD

**Issue by RylanSchaeffer** [cogtoolslab/physics-benchmarking-neurips2021#47]
@felixbinder , could you augment the [README for the human experiments](https://github.com/cogtoolslab/physics-benchmarking-neurips2021/tree/master/experiments) to explain the necessary steps to create the MongoDB and ensure the JS code can connect to it?

**Comment by judithfan** [comment]
Hi @RylanSchaeffer, thanks for your question. The steps for creating the MongoDB itself is beyond the scope of this documentation. May I suggest that you and I follow up off-line about any technical questions you have re: reproducing our web experiment infrastructure? Thanks!

**Comment by RylanSchaeffer** [comment]
@judithfan happy to! I'll email you and cc Dan Yamins.
