### ISSUE TITLE
from neuralphys.models.rpin import Net import error

### ISSUE THREAD

**Issue by Cheng-Xue** [cogtoolslab/physics-benchmarking-neurips2021#53]
Hi

I was trying to run the RPIN model and was bumped into this import error

`ModuleNotFoundError: No module named 'neuralphys'` 

It seems like neuralphys is not an open-source package that I can download. 

Also would you please explain how I can run the DPI model?

It seems like the model takes as input some preprocessed dataset that is different from other H5 files.

Any help is appreciated.

**Comment by htung0101** [comment]
Hi @Cheng-Xue: For training and evaluting the DPI model, please refer to this repo: https://github.com/htung0101/Physion-particles

**Comment by Cheng-Xue** [comment]
> 

Thanks!
